FROM python:3.9-slim

WORKDIR /app

COPY forwarder/app/main.py /app/main.py

COPY forwarder/app/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]