apiVersion: apps/v1
kind: Deployment
metadata:
  name: numbers-api
  labels:
    app: numbers-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: numbers-api
  template:
    metadata:
      labels:
        app: numbers-api
    spec:
      containers:
      - name: numbers-api
        image: 905418359591.dkr.ecr.us-east-1.amazonaws.com/numbers-api:v1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "dev"
      imagePullSecrets:
      - name: ecr-secret
