name: EKS Creation

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'create'
        options:
          - create
          - delete
      cluster_name:
        description: 'Name of the EKS cluster'
        required: true
        default: 'default-cluster'
        type: string

jobs:
  terraform:
    name: Infra Creation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5

      - name: Initialize Terraform
        working-directory: ./terraform/eksCreationJob
        run: terraform init 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1 

      - name: Terraform Workspace
        working-directory: ./terraform/eksCreationJob
        run: terraform workspace select ${{ github.event.inputs.cluster_name }} || terraform workspace new ${{ github.event.inputs.cluster_name }}

      - name: Terraform Plan
        working-directory: ./terraform/ciReleaseJob/eksCreationJob
        id: plan
        run: terraform plan -var="cluster_name=${{ github.event.inputs.cluster_name }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1  

      - name: Apply Terraform 
        if: ${{ github.event.inputs.action == 'create' }}
        working-directory: ./terraform/eksCreationJob
        run: terraform apply -auto-approve -var="cluster_name=${{ github.event.inputs.cluster_name }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1  

      - name: Destroy Terraform 
        if: ${{ github.event.inputs.action == 'delete' }}
        working-directory: ./terraform/eksCreationJob
        run: terraform destroy -auto-approve -var="cluster_name=${{ github.event.inputs.cluster_name }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Check for Errors
        if: failure()
        run: echo "An error occurred during the Terraform process."
